/* SAIYD.AI — built-in UN dangerous goods database (98 common entries, all classes)
   Source: UN Dangerous Goods List. PI columns are typical references — ALWAYS verify in current IATA DGR 4.2. */
window.SAIYD_UNDB = [
{"un":"UN0012","psn":"Cartridges for weapons, inert projectile (Cartridges, small arms)","cls":"1.4S","sub":"","pg":"II","labels":"Explosive 1.4","note":"","pipax":"130","picao":"130"},
{"un":"UN0323","psn":"Cartridges, power device","cls":"1.4S","sub":"","pg":"II","labels":"Explosive 1.4","note":"","pipax":"","picao":""},
{"un":"UN0336","psn":"Fireworks","cls":"1.4G","sub":"","pg":"II","labels":"Explosive 1.4","note":"Forbidden on passenger aircraft","pipax":"FORBIDDEN","picao":"135"},
{"un":"UN0337","psn":"Fireworks","cls":"1.4S","sub":"","pg":"II","labels":"Explosive 1.4","note":"","pipax":"135","picao":"135"},
{"un":"UN0432","psn":"Articles, pyrotechnic for technical purposes","cls":"1.4S","sub":"","pg":"II","labels":"Explosive 1.4","note":"","pipax":"135","picao":"135"},
{"un":"UN1011","psn":"Butane","cls":"2.1","sub":"","pg":"","labels":"Flammable gas","note":"CAO only","pipax":"FORBIDDEN","picao":"200"},
{"un":"UN1057","psn":"Lighters or Lighter refills (containing flammable gas)","cls":"2.1","sub":"","pg":"","labels":"Flammable gas","note":"CAO only","pipax":"FORBIDDEN","picao":"201"},
{"un":"UN1950","psn":"Aerosols, flammable","cls":"2.1","sub":"","pg":"","labels":"Flammable gas","note":"","pipax":"203","picao":"203"},
{"un":"UN1965","psn":"Hydrocarbon gas mixture, liquefied, n.o.s.","cls":"2.1","sub":"","pg":"","labels":"Flammable gas","note":"CAO only","pipax":"FORBIDDEN","picao":"200"},
{"un":"UN1978","psn":"Propane","cls":"2.1","sub":"","pg":"","labels":"Flammable gas","note":"CAO only","pipax":"FORBIDDEN","picao":"200"},
{"un":"UN2037","psn":"Gas cartridges (flammable) without release device, non-refillable","cls":"2.1","sub":"","pg":"","labels":"Flammable gas","note":"","pipax":"203","picao":"203"},
{"un":"UN3358","psn":"Refrigerating machines containing flammable, non-toxic, liquefied gas","cls":"2.1","sub":"","pg":"","labels":"Flammable gas","note":"","pipax":"","picao":""},
{"un":"UN1002","psn":"Air, compressed","cls":"2.2","sub":"","pg":"","labels":"Non-flammable gas","note":"","pipax":"200","picao":"200"},
{"un":"UN1013","psn":"Carbon dioxide","cls":"2.2","sub":"","pg":"","labels":"Non-flammable gas","note":"","pipax":"200","picao":"200"},
{"un":"UN1044","psn":"Fire extinguishers with compressed or liquefied gas","cls":"2.2","sub":"","pg":"","labels":"Non-flammable gas","note":"","pipax":"213","picao":"213"},
{"un":"UN1066","psn":"Nitrogen, compressed","cls":"2.2","sub":"","pg":"","labels":"Non-flammable gas","note":"","pipax":"200","picao":"200"},
{"un":"UN1072","psn":"Oxygen, compressed","cls":"2.2","sub":"5.1","pg":"","labels":"Non-flammable gas + Oxidizer","note":"","pipax":"200","picao":"200"},
{"un":"UN1080","psn":"Sulphur hexafluoride","cls":"2.2","sub":"","pg":"","labels":"Non-flammable gas","note":"","pipax":"200","picao":"200"},
{"un":"UN1950","psn":"Aerosols, non-flammable","cls":"2.2","sub":"","pg":"","labels":"Non-flammable gas","note":"","pipax":"203","picao":"203"},
{"un":"UN1977","psn":"Nitrogen, refrigerated liquid","cls":"2.2","sub":"","pg":"","labels":"Non-flammable gas","note":"","pipax":"202","picao":"202"},
{"un":"UN2857","psn":"Refrigerating machines containing non-flammable, non-toxic gases","cls":"2.2","sub":"","pg":"","labels":"Non-flammable gas","note":"","pipax":"","picao":""},
{"un":"UN3164","psn":"Articles, pressurized, pneumatic or hydraulic","cls":"2.2","sub":"","pg":"","labels":"Non-flammable gas","note":"","pipax":"","picao":""},
{"un":"UN1005","psn":"Ammonia, anhydrous","cls":"2.3","sub":"8","pg":"","labels":"Toxic gas + Corrosive","note":"Forbidden on passenger aircraft","pipax":"FORBIDDEN","picao":"200"},
{"un":"UN1017","psn":"Chlorine","cls":"2.3","sub":"5.1, 8","pg":"","labels":"Toxic gas + Oxidizer + Corrosive","note":"FORBIDDEN by air (PAX and CAO)","pipax":"FORBIDDEN","picao":"FORBIDDEN"},
{"un":"UN1090","psn":"Acetone","cls":"3","sub":"","pg":"II","labels":"Flammable liquid","note":"","pipax":"353","picao":"364"},
{"un":"UN1133","psn":"Adhesives, containing flammable liquid","cls":"3","sub":"","pg":"I/II/III","labels":"Flammable liquid","note":"","pipax":"351(I) 353(II) 355(III)","picao":"361(I) 364(II) 366(III)"},
{"un":"UN1170","psn":"Ethanol (Ethyl alcohol) or Ethanol solution","cls":"3","sub":"","pg":"II/III","labels":"Flammable liquid","note":"","pipax":"353(II) 355(III)","picao":"364(II) 366(III)"},
{"un":"UN1197","psn":"Extracts, flavouring, liquid","cls":"3","sub":"","pg":"II/III","labels":"Flammable liquid","note":"","pipax":"353(II) 355(III)","picao":"364(II) 366(III)"},
{"un":"UN1203","psn":"Gasoline (Petrol)","cls":"3","sub":"","pg":"II","labels":"Flammable liquid","note":"","pipax":"353","picao":"364"},
{"un":"UN1210","psn":"Printing ink, flammable or Printing ink related material","cls":"3","sub":"","pg":"I/II/III","labels":"Flammable liquid","note":"","pipax":"351(I) 353(II) 355(III)","picao":"361(I) 364(II) 366(III)"},
{"un":"UN1219","psn":"Isopropanol (Isopropyl alcohol)","cls":"3","sub":"","pg":"II","labels":"Flammable liquid","note":"","pipax":"353","picao":"364"},
{"un":"UN1230","psn":"Methanol","cls":"3","sub":"6.1","pg":"II","labels":"Flammable liquid + Toxic","note":"","pipax":"352","picao":"364"},
{"un":"UN1263","psn":"Paint or Paint related material","cls":"3","sub":"","pg":"I/II/III","labels":"Flammable liquid","note":"","pipax":"351(I) 353(II) 355(III)","picao":"361(I) 364(II) 366(III)"},
{"un":"UN1266","psn":"Perfumery products with flammable solvents","cls":"3","sub":"","pg":"II/III","labels":"Flammable liquid","note":"PG II (FP<23C): PAX 5 L (LQ Y341 1 L), CAO 60 L. PG III (FP 23-60C): PAX 60 L (LQ Y344 10 L), CAO 220 L. USA: 24-hr emergency phone mandatory. Retail-packed? Consider ID8000.","pipax":"353(II) 355(III)","picao":"364(II) 366(III)"},
{"un":"UN1268","psn":"Petroleum distillates, n.o.s. or Petroleum products, n.o.s.","cls":"3","sub":"","pg":"I/II/III","labels":"Flammable liquid","note":"","pipax":"351(I) 353(II) 355(III)","picao":"361(I) 364(II) 366(III)"},
{"un":"UN1307","psn":"Xylenes","cls":"3","sub":"","pg":"II/III","labels":"Flammable liquid","note":"","pipax":"353(II) 355(III)","picao":"364(II) 366(III)"},
{"un":"UN1863","psn":"Fuel, aviation, turbine engine","cls":"3","sub":"","pg":"I/II/III","labels":"Flammable liquid","note":"","pipax":"351(I) 353(II) 355(III)","picao":"361(I) 364(II) 366(III)"},
{"un":"UN1866","psn":"Resin solution, flammable","cls":"3","sub":"","pg":"I/II/III","labels":"Flammable liquid","note":"","pipax":"351(I) 353(II) 355(III)","picao":"361(I) 364(II) 366(III)"},
{"un":"UN1987","psn":"Alcohols, n.o.s.","cls":"3","sub":"","pg":"II/III","labels":"Flammable liquid","note":"","pipax":"353(II) 355(III)","picao":"364(II) 366(III)"},
{"un":"UN1993","psn":"Flammable liquid, n.o.s.","cls":"3","sub":"","pg":"I/II/III","labels":"Flammable liquid","note":"Technical name required","pipax":"351(I) 353(II) 355(III)","picao":"361(I) 364(II) 366(III)"},
{"un":"UN3065","psn":"Alcoholic beverages (over 24% alcohol)","cls":"3","sub":"","pg":"II/III","labels":"Flammable liquid","note":"","pipax":"353(II) 355(III)","picao":"364(II) 366(III)"},
{"un":"UN3269","psn":"Polyester resin kit, liquid base material","cls":"3","sub":"","pg":"II/III","labels":"Flammable liquid","note":"","pipax":"","picao":""},
{"un":"UN1350","psn":"Sulphur","cls":"4.1","sub":"","pg":"III","labels":"Flammable solid","note":"","pipax":"446","picao":"449"},
{"un":"UN1944","psn":"Matches, safety","cls":"4.1","sub":"","pg":"III","labels":"Flammable solid","note":"","pipax":"","picao":""},
{"un":"UN3175","psn":"Solids containing flammable liquid, n.o.s.","cls":"4.1","sub":"","pg":"II","labels":"Flammable solid","note":"Technical name required","pipax":"445","picao":"448"},
{"un":"UN3089","psn":"Metal powder, flammable, n.o.s.","cls":"4.1","sub":"","pg":"II/III","labels":"Flammable solid","note":"","pipax":"445(II) 446(III)","picao":"448(II) 449(III)"},
{"un":"UN1362","psn":"Carbon, activated","cls":"4.2","sub":"","pg":"III","labels":"Spontaneously combustible","note":"","pipax":"","picao":""},
{"un":"UN3088","psn":"Self-heating solid, organic, n.o.s.","cls":"4.2","sub":"","pg":"II/III","labels":"Spontaneously combustible","note":"Technical name required","pipax":"","picao":""},
{"un":"UN1396","psn":"Aluminium powder, uncoated","cls":"4.3","sub":"","pg":"II/III","labels":"Dangerous when wet","note":"","pipax":"","picao":""},
{"un":"UN3208","psn":"Metallic substance, water-reactive, n.o.s.","cls":"4.3","sub":"","pg":"I/II/III","labels":"Dangerous when wet","note":"Technical name required","pipax":"","picao":""},
{"un":"UN1479","psn":"Oxidizing solid, n.o.s.","cls":"5.1","sub":"","pg":"I/II/III","labels":"Oxidizer","note":"Technical name required","pipax":"","picao":""},
{"un":"UN1748","psn":"Calcium hypochlorite, dry","cls":"5.1","sub":"","pg":"II/III","labels":"Oxidizer","note":"","pipax":"","picao":""},
{"un":"UN1942","psn":"Ammonium nitrate (with not more than 0.2% combustible substances)","cls":"5.1","sub":"","pg":"III","labels":"Oxidizer","note":"","pipax":"","picao":""},
{"un":"UN2067","psn":"Ammonium nitrate based fertilizer","cls":"5.1","sub":"","pg":"III","labels":"Oxidizer","note":"","pipax":"","picao":""},
{"un":"UN3139","psn":"Oxidizing liquid, n.o.s.","cls":"5.1","sub":"","pg":"I/II/III","labels":"Oxidizer","note":"Technical name required","pipax":"","picao":""},
{"un":"UN3105","psn":"Organic peroxide type D, liquid","cls":"5.2","sub":"","pg":"","labels":"Organic peroxide","note":"Technical name required","pipax":"","picao":""},
{"un":"UN3108","psn":"Organic peroxide type E, solid","cls":"5.2","sub":"","pg":"","labels":"Organic peroxide","note":"Technical name required","pipax":"","picao":""},
{"un":"UN1593","psn":"Dichloromethane","cls":"6.1","sub":"","pg":"III","labels":"Toxic","note":"","pipax":"","picao":""},
{"un":"UN2810","psn":"Toxic liquid, organic, n.o.s.","cls":"6.1","sub":"","pg":"I/II/III","labels":"Toxic","note":"Technical name required","pipax":"","picao":""},
{"un":"UN2811","psn":"Toxic solid, organic, n.o.s.","cls":"6.1","sub":"","pg":"I/II/III","labels":"Toxic","note":"Technical name required","pipax":"","picao":""},
{"un":"UN2831","psn":"1,1,1-Trichloroethane","cls":"6.1","sub":"","pg":"III","labels":"Toxic","note":"","pipax":"","picao":""},
{"un":"UN3288","psn":"Toxic solid, inorganic, n.o.s.","cls":"6.1","sub":"","pg":"I/II/III","labels":"Toxic","note":"Technical name required","pipax":"","picao":""},
{"un":"UN1888","psn":"Chloroform","cls":"6.1","sub":"","pg":"III","labels":"Toxic","note":"","pipax":"","picao":""},
{"un":"UN2814","psn":"Infectious substance, affecting humans","cls":"6.2","sub":"","pg":"","labels":"Infectious substance","note":"Category A - special provisions apply","pipax":"620","picao":"620"},
{"un":"UN3373","psn":"Biological substance, Category B","cls":"6.2","sub":"","pg":"","labels":"(PI650 marking)","note":"DGD not required if fully per PI 650 - verify","pipax":"650","picao":"650"},
{"un":"UN3291","psn":"Clinical waste, unspecified, n.o.s.","cls":"6.2","sub":"","pg":"II","labels":"Infectious substance","note":"","pipax":"622","picao":"622"},
{"un":"UN2908","psn":"Radioactive material, excepted package - empty packaging","cls":"7","sub":"","pg":"","labels":"(Excepted)","note":"DGD generally not required - verify DGR 10","pipax":"See DGR 10","picao":"See DGR 10"},
{"un":"UN2910","psn":"Radioactive material, excepted package - limited quantity of material","cls":"7","sub":"","pg":"","labels":"(Excepted)","note":"DGD generally not required - verify DGR 10","pipax":"See DGR 10","picao":"See DGR 10"},
{"un":"UN2911","psn":"Radioactive material, excepted package - instruments or articles","cls":"7","sub":"","pg":"","labels":"(Excepted)","note":"DGD generally not required - verify DGR 10","pipax":"See DGR 10","picao":"See DGR 10"},
{"un":"UN2915","psn":"Radioactive material, Type A package","cls":"7","sub":"","pg":"","labels":"RA I / II / III per category","note":"Radioactive shipments: use DGR Section 10","pipax":"See DGR 10","picao":"See DGR 10"},
{"un":"UN1760","psn":"Corrosive liquid, n.o.s.","cls":"8","sub":"","pg":"I/II/III","labels":"Corrosive","note":"Technical name required","pipax":"850(I) 851(II) 852(III)","picao":"854(I) 855(II) 856(III)"},
{"un":"UN1789","psn":"Hydrochloric acid","cls":"8","sub":"","pg":"II/III","labels":"Corrosive","note":"","pipax":"851(II) 852(III)","picao":"855(II) 856(III)"},
{"un":"UN1805","psn":"Phosphoric acid solution","cls":"8","sub":"","pg":"III","labels":"Corrosive","note":"","pipax":"852","picao":"856"},
{"un":"UN1824","psn":"Sodium hydroxide solution","cls":"8","sub":"","pg":"II/III","labels":"Corrosive","note":"","pipax":"851(II) 852(III)","picao":"855(II) 856(III)"},
{"un":"UN1830","psn":"Sulphuric acid (more than 51% acid)","cls":"8","sub":"","pg":"II","labels":"Corrosive","note":"","pipax":"851","picao":"855"},
{"un":"UN2209","psn":"Formaldehyde solution (with not less than 25% formaldehyde)","cls":"8","sub":"","pg":"III","labels":"Corrosive","note":"","pipax":"852","picao":"856"},
{"un":"UN2794","psn":"Batteries, wet, filled with acid","cls":"8","sub":"","pg":"","labels":"Corrosive","note":"","pipax":"870","picao":"870"},
{"un":"UN2795","psn":"Batteries, wet, filled with alkali","cls":"8","sub":"","pg":"","labels":"Corrosive","note":"","pipax":"870","picao":"870"},
{"un":"UN2796","psn":"Battery fluid, acid","cls":"8","sub":"","pg":"II","labels":"Corrosive","note":"","pipax":"851","picao":"855"},
{"un":"UN2800","psn":"Batteries, wet, non-spillable","cls":"8","sub":"","pg":"","labels":"Corrosive","note":"May be excepted per SP A67 - verify","pipax":"872","picao":"872"},
{"un":"UN3262","psn":"Corrosive solid, basic, inorganic, n.o.s.","cls":"8","sub":"","pg":"I/II/III","labels":"Corrosive","note":"Technical name required","pipax":"859(II) 860(III)","picao":"863(II) 864(III)"},
{"un":"UN3264","psn":"Corrosive liquid, acidic, inorganic, n.o.s.","cls":"8","sub":"","pg":"I/II/III","labels":"Corrosive","note":"Technical name required","pipax":"850(I) 851(II) 852(III)","picao":"854(I) 855(II) 856(III)"},
{"un":"UN1845","psn":"Carbon dioxide, solid (Dry ice)","cls":"9","sub":"","pg":"","labels":"Miscellaneous","note":"DGD not required unless with other DG - verify PI 954","pipax":"954","picao":"954"},
{"un":"UN2807","psn":"Magnetized material","cls":"9","sub":"","pg":"","labels":"(Magnetized material label)","note":"DGD not required - verify PI 953","pipax":"953","picao":"953"},
{"un":"UN3077","psn":"Environmentally hazardous substance, solid, n.o.s.","cls":"9","sub":"","pg":"III","labels":"Miscellaneous + Env. hazard","note":"Technical name required","pipax":"956","picao":"956"},
{"un":"UN3082","psn":"Environmentally hazardous substance, liquid, n.o.s.","cls":"9","sub":"","pg":"III","labels":"Miscellaneous + Env. hazard","note":"Technical name required","pipax":"964","picao":"964"},
{"un":"UN3090","psn":"Lithium metal batteries","cls":"9","sub":"","pg":"","labels":"Lithium battery + CAO","note":"CAO only (Section IA/IB). PI 968","pipax":"FORBIDDEN","picao":"968"},
{"un":"UN3091","psn":"Lithium metal batteries packed with equipment or contained in equipment","cls":"9","sub":"","pg":"","labels":"Lithium battery","note":"PI 969 / 970","pipax":"969 / 970","picao":"969 / 970"},
{"un":"UN3166","psn":"Vehicle, flammable gas powered or Vehicle, flammable liquid powered","cls":"9","sub":"","pg":"","labels":"Miscellaneous","note":"PI 950/951","pipax":"950 / 951","picao":"950 / 951"},
{"un":"UN3171","psn":"Battery-powered vehicle or Battery-powered equipment","cls":"9","sub":"","pg":"","labels":"Miscellaneous","note":"PI 952","pipax":"952","picao":"952"},
{"un":"UN3245","psn":"Genetically modified organisms / micro-organisms","cls":"9","sub":"","pg":"","labels":"Miscellaneous","note":"","pipax":"959","picao":"959"},
{"un":"UN3268","psn":"Safety devices, electrically initiated (e.g. air bag modules)","cls":"9","sub":"","pg":"III","labels":"Miscellaneous","note":"PI 961","pipax":"961","picao":"961"},
{"un":"UN3316","psn":"Chemical kit or First aid kit","cls":"9","sub":"","pg":"II/III","labels":"Miscellaneous","note":"","pipax":"960","picao":"960"},
{"un":"UN3363","psn":"Dangerous goods in machinery or Dangerous goods in apparatus","cls":"9","sub":"","pg":"","labels":"Miscellaneous","note":"PI 962","pipax":"962","picao":"962"},
{"un":"UN3480","psn":"Lithium ion batteries","cls":"9","sub":"","pg":"","labels":"Lithium battery + CAO","note":"CAO only (Section IA/IB). PI 965","pipax":"FORBIDDEN","picao":"965"},
{"un":"UN3481","psn":"Lithium ion batteries packed with equipment or contained in equipment","cls":"9","sub":"","pg":"","labels":"Lithium battery","note":"PI 966 / 967","pipax":"966 / 967","picao":"966 / 967"},
{"un":"UN3536","psn":"Lithium batteries installed in cargo transport unit","cls":"9","sub":"","pg":"","labels":"Miscellaneous","note":"","pipax":"","picao":""},
{"un":"ID8000","psn":"Consumer commodity","cls":"9","sub":"","pg":"","labels":"Miscellaneous","note":"Retail-packed perfume/cosmetics/aerosols. PI Y963, max 30 kg G per package. Very common for perfume to USA. Check DGR 2.7 + operator variations.","pipax":"Y963","picao":"Y963"}
];
